### ISSUE TITLE
EmrClient createCluster is not working as expected. 

### ISSUE THREAD

**Issue by scmacdon** [awslabs/aws-sdk-kotlin#439] opened 2021-11-22 16:19 UTC
## Describe the bug

This code is not working, It says try again later.

suspend fun createAppCluster(
    jarVal: String?,
    myClassVal: String?,
    keysVal: String?,
    logUriVal: String?,
    nameVal: String?
): String? {

        val jarStepConfig = HadoopJarStepConfig {
            jar = jarVal
            mainClass = myClassVal
        }

        val spark = Application {
            name = "Spark"
        }

        val hive = Application {
            name = "Hive"
        }
        val zeppelin = Application {
            name = "Zeppelin"
        }

        val apps = mutableListOf<Application>()
        apps.add(spark)
        apps.add(hive)
        apps.add(zeppelin)

        val enabledebugging = StepConfig {
            name = "Enable debugging"
            actionOnFailure = ActionOnFailure.fromValue("TERMINATE_JOB_FLOW")
            hadoopJarStep = jarStepConfig
        }
        val instancesConfig  = JobFlowInstancesConfig {
             ec2SubnetId = "subnet-206a9c58"
             ec2KeyName = keysVal
             instanceCount = 3
             keepJobFlowAliveWhenNoSteps = true
             masterInstanceType = "m4.large"
             slaveInstanceType = "m4.large"
        }

        val request = RunJobFlowRequest {
            name = nameVal
            releaseLabel = "emr-5.20.0"
            steps = listOf(enabledebugging)
            applications = apps
            logUri = logUriVal
            serviceRole = "EMR_DefaultRole"
            jobFlowRole = "EMR_EC2_DefaultRole"
            instances = instancesConfig
        }

        EmrClient { region = "us-west-2" }.use { emrClient ->
            val response: RunJobFlowResponse = emrClient.runJobFlow(request)
            return response.jobFlowId
        }
 }

## Your Environment

* AWS Kotlin SDK version used:
* Platform (JVM/JS/Native):
* Operating System and version:

**Comment by ianbotsf** [comment] 2021-11-22 18:53
I am unable to reproduce this issue so far. I copied/pasted the code but had to change a few things for my own AWS account such as the `ec2SubnetId`.

Can you please attach a full code sample and Gradle build file?

**Comment by ianbotsf** [comment] 2021-11-23 18:39
Submitter confirmed sample is working correctly now. Resolving issue.

**Closed by ianbotsf** 2021-11-23 18:39 UTC
Labels: bug
