### ISSUE TITLE
Assume Role support

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-sdk-kotlin#235] opened 2021-05-12 22:57 UTC
SEP: /seps/accepted/shared/assume-role.md

**Comment by kmbotts** [comment] 2021-09-06 13:07
Added support to override using JVM System Property here: https://github.com/awslabs/aws-sdk-kotlin/pull/312

**Comment by aajtodd** [comment] 2021-09-27 16:56
Likely duplicate of: https://github.com/awslabs/aws-sdk-kotlin/issues/19

**Closed as completed** 2021-10-27 18:40 UTC
Labels: feature-request
