### ISSUE TITLE
Add a paginated query member or extension API to dynamodb

### ISSUE THREAD

**Issue by efemoney** [awslabs/aws-sdk-kotlin#456] opened 2021-12-02 09:12 UTC
### Describe the feature

SDK should include an API for paginating `Query`s

### Is your Feature Request related to a problem?

It would be great to improve developer experience.

### Proposed Solution

Hand rolled my own extension function.

```kotlin
suspend fun DynamoDbClient.paginatedQuery(input: QueryRequest): QueryResponse {
  var response = query(input)

  while (response.lastEvaluatedKey != null) {
    val newResponse = query(input.copy { exclusiveStartKey = response.lastEvaluatedKey })
    response = newResponse.copy {
      items = response.items.orEmpty() + items.orEmpty()
      count += response.count
    }
  }

  return response
}

suspend fun DynamoDbClient.paginatedQuery(builder: QueryRequest.Builder.() -> Unit) =
  paginatedQuery(QueryRequest { builder() })
```

### Acknowledge

- [x] I may be able to implement this feature request

### AWS Kotlin SDK version used

0.9.3-alpha

### Platform (JVM/JS/Native)

JVM (JDK 16)

### Operating System and version

MacOS Monterey

**Comment by aajtodd** [comment] 2021-12-02 14:44
@efemoney Thanks for the feature request.

Paginators are on the [roadmap](https://github.com/awslabs/aws-sdk-kotlin/projects/2#card-64638442) already. There is also a preliminary design [here](https://github.com/awslabs/smithy-kotlin/blob/main/docs/design/paginators.md).

I'm going to close this as a duplicate of [smithy-kotlin#124](https://github.com/awslabs/smithy-kotlin/issues/124). Feel free to upvote that issue or leave feedback on the proposed design there.

**Closed by aajtodd** 2021-12-02 14:44 UTC
Labels: duplicate, feature-request
