### ISSUE TITLE
Use of AwsEndpointResolver in 0.9.0 throws an java.lang.ClassCastException

### ISSUE THREAD

**Issue by scmacdon** [awslabs/aws-sdk-kotlin#401] opened 2021-11-03 16:08 UTC
## Describe the bug
WHen the following code in Media Convert is used: 

suspend fun main() {

    val mcClient = MediaConvertClient{region="us-west-2"}
    listCompleteJobs(mcClient)
}

// snippet-start:[mediaconvert.kotlin.list_jobs.main]
suspend fun listCompleteJobs(mcClient: MediaConvertClient) {

    try {

        val describeEndpoints = DescribeEndpointsRequest {
            maxResults = 20
        }

        val res = mcClient.describeEndpoints(describeEndpoints)

        if (res.endpoints?.size!! <= 0) {
            println("Cannot find MediaConvert service endpoint URL!")
            exitProcess(0)
        }
        val endpointURL = res.endpoints!!.get(0).url.toString()
        val uri = URI(endpointURL)
        val domain = uri.host

        **val client = MediaConvertClient  {
            endpointResolver = AwsEndpointResolver { service, region ->
                AwsEndpoint(domain, CredentialScope(region = "us-west-2"))
            }
        }**

...

This exception is thrown: 

Exception in thread "main" java.lang.ClassCastException: com.kotlin.mediaconvert.ListJobsKt$listCompleteJobs$client$1$1 cannot be cast to aws.sdk.kotlin.runtime.endpoint.AwsEndpointResolver
	at com.kotlin.mediaconvert.ListJobsKt$listCompleteJobs$client$1.invoke(ListJobs.kt:69)
	at com.kotlin.mediaconvert.ListJobsKt$listCompleteJobs$client$1.invoke(ListJobs.kt)
	at aws.sdk.kotlin.services.mediaconvert.MediaConvertClient$Companion.invoke(MediaConvertClient.kt:46)
	at aws.sdk.kotlin.services.mediaconvert.MediaConvertClient$Companion.invoke$default(MediaConvertClient.kt:42)
	at com.kotlin.mediaconvert.ListJobsKt.listCompleteJobs(ListJobs.kt:68)
	at com.kotlin.mediaconvert.ListJobsKt$listCompleteJobs$1.invokeSuspend(ListJobs.kt)

## Expected Behavior
It should work accoring to this doc: 

https://github.com/awslabs/aws-sdk-kotlin/blob/main/docs/howto/configuring/endpoints.md

## Your Environment

* AWS Kotlin SDK version used:
* Platform (JVM/JS/Native):
* Operating System and version:

**Comment by ianbotsf** [comment] 2021-11-03 22:43
I cannot reproduce the specific error given in this issue description (`ClassCastException`). Instead, I get `java.lang.IllegalArgumentException: region is a required configuration property` when instantiating the second `MediaConvertClient`. The solution there is to include `region` in the client construction block:

```kotlin
val client = MediaConvertClient {
    region = "us-west-2" // ← This part was missing
    endpointResolver = AwsEndpointResolver { service, region ->
        AwsEndpoint(endpointURL, CredentialScope(region = "us-west-2"))
    }
}
```

Once I added that, I got another error trying to actually utilize the endpoint resolver: `java.lang.NullPointerException: uri.scheme must not be null`. It looks like the code provided parses the endpoints returned from `describeEndpoints` and extracts only the host information (e.g., **foo.mediaconvert.us-west-2.amazonaws.com**). Endpoint resolvers need to return values that include the scheme as well (e.g., **https://**). Thus, it's simpler to skip parsing the returned endpoint from `describeEndpoints` and use the value directly:

```kotlin
val endpointURL = res.endpoints!!.get(0).url!!

val client = MediaConvertClient {
    region = "us-west-2"
    endpointResolver = AwsEndpointResolver { service, region ->
        AwsEndpoint(endpointURL, CredentialScope(region = "us-west-2"))
    }
}
```

Once these changes are made, I'm able to use the second `MediaConvertClient` to make calls (e.g., `listJobs`) that complete successfully against the specified endpoint.

Does that resolve this issue?

**Comment by ianbotsf** [comment] 2021-11-04 15:53
After further investigation, the code fails in versions of Kotlin that don't have [support for `suspend` functions in functional interfaces](https://youtrack.jetbrains.com/issue/KT-44787) (i.e., < 1.5.0). Downgrading my test code to 1.4.10 allowed me to reproduce the issue.

For now, the SDK cannot commit to supporting versions of Kotlin prior to the current minor version. (Currently, that means 1.5.x is supported. Versions before 1.5 are unsupported.)

Resolving this issue with the fix being to upgrade to the latest supported version of Kotlin.

**Closed by ianbotsf** 2021-11-04 15:53 UTC
Labels: bug
