### ISSUE TITLE
GetObject Partial Response Validation

### ISSUE THREAD

**Issue by aajtodd** [awslabs/aws-sdk-kotlin#745] opened 2022-11-08 14:21 UTC
### Describe the feature

S3 GetObject requests can close the connection unexpectedly before all of the Object's bytes are sent in the response. SDKs may need to explicitly ensure that the number bytes received are equal to the number of bytes in the ContentLength.

### Is your Feature Request related to a problem?

S3 SDK Feature

### Proposed Solution

Add validation to HTTP engine or possibly as a middleware/wrapped stream that validates the total data consumed matches the content length reported. Add an integration test to the HTTP engine test suite if possible.

### Describe alternative solutions or features you've considered

N/A

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Kotlin SDK version used

N/A

### Platform (JVM/JS/Native)

N/A

### Operating System and version

N/A

**Comment by lauzadis** [comment] 2022-11-08 14:58
Should we figure out the root cause of why the connections are closing unexpectedly? Is that something happening on our end or S3's? Is it just something that we expect to happen from time to time?

**Comment by aajtodd** [comment] 2022-11-08 15:01
I'm just filling out our backlog with things that need to be implemented. This is supposedly expected behavior (I have not observed it in our SDK to date though and quite frankly checksum validation would be a better solution for this).

**Comment by lauzadis** [comment] 2023-07-21 19:18
Closed by #991

**Closed by lauzadis** 2023-07-21 19:18 UTC
Labels: feature-request, module/s3
