### ISSUE TITLE
Support Browser-Based Upload using HTTP Post (AWS Sig V4)

### ISSUE THREAD

**Issue by enif-lee** [awslabs/aws-sdk-kotlin#1406] opened 2024-09-15 11:12 UTC
### Describe the feature

https://github.com/aws/aws-sdk-java-v2/issues/1493
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

This feature provide to make way rectricting content type and file size.

### Is your feature request related to a problem?

-

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS SDK for Kotlin version

1.3.32

### Platform (JVM/JS/Native)

JVM

### Operating system and version

MAC

**Comment by ianbotsf** [comment] 2024-09-16 15:25
Duplicate of https://github.com/awslabs/aws-sdk-kotlin/issues/1406.

**Closed by ianbotsf** 2024-09-16 15:25 UTC
Labels: feature-request, needs-triage
