### ISSUE TITLE
DescribeInstances hitting EOFException in Kotlin AWS SDK

### ISSUE THREAD

**Issue by mjindalmotiv8** [awslabs/aws-sdk-kotlin#503] opened 2022-01-15 21:02 UTC
### Describe the bug

Kotlin AWS SDK version - 0.9.4-beta

DescribeInstances hitting EOFException with the following stack trace. This has been observed for both IAD and PDX and we are seeing this when we are calling DescribingInstances while trying to launch instances.

> stack_trace | java.io.EOFException: no more data available - expected end tags </item></instancesSet></item></reservationSet></DescribeInstancesResponse> to close start tag <item> from line 196 and start tag <instancesSet> from line 9 and start tag <item> from line 5 and start tag <reservationSet> from line 4 and start tag <DescribeInstancesResponse> from line 2, parser stopped on END_TAG seen ...</iamInstanceProfile>\n ... @320:5at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1384)at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)at aws.smithy.kotlin.runtime.serde.xml.XmlStreamReaderXmlPull.takeNextValidToken(XmlStreamReaderXmlPull.kt:122)at aws.smithy.kotlin.runtime.serde.xml.XmlStreamReaderXmlPull.internalPeek(XmlStreamReaderXmlPull.kt:96)at aws.smithy.kotlin.runtime.serde.xml.XmlStreamReaderXmlPull.peek(XmlStreamReaderXmlPull.kt:89)at aws.smithy.kotlin.runtime.serde.xml.SubTreeReader.nextToken(XmlStreamReaderXmlPull.kt:204)at aws.smithy.kotlin.runtime.serde.xml.XmlStructDeserializer.findNextFieldIndex(XmlDeserializer.kt:217)at aws.smithy.kotlin.runtime.serde.xml.XmlStructDeserializer.findNextFieldIndex(XmlDeserializer.kt:219)at aws.sdk.kotlin.services.ec2.transform.IamInstanceProfileDocumentDeserializerKt.deserializeIamInstanceProfileDocument(IamInstanceProfileDocumentDeserializer.kt:36)at aws.sdk.kotlin.services.ec2.transform.InstanceDocumentDeserializerKt.deserializeInstanceDocument(InstanceDocumentDeserializer.kt:194)at aws.sdk.kotlin.services.ec2.transform.ReservationDocumentDeserializerKt.deserializeReservationDocument(ReservationDocumentDeserializer.kt:59)at aws.sdk.kotlin.services.ec2.transform.DescribeInstancesOperationDeserializerKt.deserializeDescribeInstancesOperationBody(DescribeInstancesOperationDeserializer.kt:69)at aws.sdk.kotlin.services.ec2.transform.DescribeInstancesOperationDeserializerKt.access$deserializeDescribeInstancesOperationBody(DescribeInstancesOperationDeserializer.kt:1)at aws.sdk.kotlin.services.ec2.transform.DescribeInstancesOperationDeserializer.deserialize(DescribeInstancesOperationDeserializer.kt:44)at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:153)at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt)at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)at java.base/java.lang.Thread.run(Thread.java:833)

### Expected behavior

DescribeInstances should not return an excpetion

### Current behavior

> stack_trace | java.io.EOFException: no more data available - expected end tags </item></instancesSet></item></reservationSet></DescribeInstancesResponse> to close start tag <item> from line 196 and start tag <instancesSet> from line 9 and start tag <item> from line 5 and start tag <reservationSet> from line 4 and start tag <DescribeInstancesResponse> from line 2, parser stopped on END_TAG seen ...</iamInstanceProfile>\n ... @320:5at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1384)at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)at aws.smithy.kotlin.runtime.serde.xml.XmlStreamReaderXmlPull.takeNextValidToken(XmlStreamReaderXmlPull.kt:122)at aws.smithy.kotlin.runtime.serde.xml.XmlStreamReaderXmlPull.internalPeek(XmlStreamReaderXmlPull.kt:96)at aws.smithy.kotlin.runtime.serde.xml.XmlStreamReaderXmlPull.peek(XmlStreamReaderXmlPull.kt:89)at aws.smithy.kotlin.runtime.serde.xml.SubTreeReader.nextToken(XmlStreamReaderXmlPull.kt:204)at aws.smithy.kotlin.runtime.serde.xml.XmlStructDeserializer.findNextFieldIndex(XmlDeserializer.kt:217)at aws.smithy.kotlin.runtime.serde.xml.XmlStructDeserializer.findNextFieldIndex(XmlDeserializer.kt:219)at aws.sdk.kotlin.services.ec2.transform.IamInstanceProfileDocumentDeserializerKt.deserializeIamInstanceProfileDocument(IamInstanceProfileDocumentDeserializer.kt:36)at aws.sdk.kotlin.services.ec2.transform.InstanceDocumentDeserializerKt.deserializeInstanceDocument(InstanceDocumentDeserializer.kt:194)at aws.sdk.kotlin.services.ec2.transform.ReservationDocumentDeserializerKt.deserializeReservationDocument(ReservationDocumentDeserializer.kt:59)at aws.sdk.kotlin.services.ec2.transform.DescribeInstancesOperationDeserializerKt.deserializeDescribeInstancesOperationBody(DescribeInstancesOperationDeserializer.kt:69)at aws.sdk.kotlin.services.ec2.transform.DescribeInstancesOperationDeserializerKt.access$deserializeDescribeInstancesOperationBody(DescribeInstancesOperationDeserializer.kt:1)at aws.sdk.kotlin.services.ec2.transform.DescribeInstancesOperationDeserializer.deserialize(DescribeInstancesOperationDeserializer.kt:44)at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)at aws.smithy.kotlin.runtime.http.operation.SdkOperationExecutionKt$decorate$3.invoke(SdkOperationExecution.kt:97)at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler.call(SdkOperationExecution.kt:153)at aws.smithy.kotlin.runtime.http.operation.DeserializeHandler$call$1.invokeSuspend(SdkOperationExecution.kt)at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to Reproduce

Code snippet
```
    override suspend fun listAllInstances(availabilityZoneName: String): List<ProviderInstanceDetails> {
        LOGGER.info { msg("listing instances for az").any("availability_zone_name", availabilityZoneName) }
        val request = DescribeInstancesRequest {
            filters = listOf(
                Filter {
                    name = "availability-zone"
                    values = listOf(availabilityZoneName)
                },
                Filter {
                    name = "tag:abcdef:fleet"
                    values = listOf("abcdfefg")
                },
                Filter {
                    name = "instance-state-name"
                    values = listOf("running")
                }
            )
        }
        val describeInstancesResponse = ec2Client.describeInstances(request)
        LOGGER.info { msg("successfully described ec2 instances").any("response", describeInstancesResponse) }

        val reservations = describeInstancesResponse.reservations
            ?: throw EC2DeployerException("no reservations found while listing instances")

        return reservations.flatMap { it.instances ?: listOf() }
            .map { it.toProviderInstanceDetails() }
    }

```

### Context

This is affecting our deployments.

### AWS Kotlin SDK version used

0.9.4-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Linux x86_64

**Comment by kggilmer** [comment] 2022-01-21 00:11
@mjindalmotiv8 , I have been unable to reproduce your bug on my end.  I'm wondering if there is some specific state in your AWS account that is related to the problem.  I've tried setting up a few EC2 instances in a test account and running the following varation on your code snippet, however when getting results back I do not see the error.  Would it be possible for you to enable debug logging so that we can get the request/response data back for further troubleshooting?  If so you'd need to add a logger dependency to your application (described in debugging.md) and specify the log mode when constructing the client (as shown below).  Or, if you have other ideas on how I could reproduce this that would be fine as well.

```kotlin
import aws.sdk.kotlin.services.ec2.Ec2Client
import aws.sdk.kotlin.services.ec2.model.DescribeInstancesRequest
import aws.sdk.kotlin.services.ec2.model.Filter
import aws.sdk.kotlin.services.ec2.model.Instance
import aws.smithy.kotlin.runtime.client.SdkLogMode
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
    Ec2Client.fromEnvironment {
        sdkLogMode = SdkLogMode.LogResponseWithBody
        region = "us-east-2"
    }.use { client ->
        println(listAllInstances("us-east-2a", client))
    }
}

suspend fun listAllInstances(availabilityZoneName: String, ec2Client: Ec2Client): List<Instance> {

    val request = DescribeInstancesRequest {
        filters = listOf(
            Filter {
                name = "availability-zone"
                values = listOf(availabilityZoneName)
            },
            Filter {
                name = "tag:abcdef:fleet"
                values = listOf("abcdfefg")
            },
            Filter {
                name = "instance-state-name"
                values = listOf("running")
            }
        )
    }
    val describeInstancesResponse = ec2Client.describeInstances(request)

    val reservations = describeInstancesResponse.reservations
        ?: error("no reservations found while listing instances")

    return reservations.flatMap { it.instances ?: listOf() }
        .map { it }
}
```

**Comment by mjindalmotiv8** [comment] 2022-01-21 17:20
We had observed it across 2 different accounts so I do not think this is account related. 

However, we have not seen this last week and this might be because of two changes we did
1) Updated to the latest SDK
2) Scaled down our instances.

I will discuss with the team if they are ok in adding more verbosity to our sdk logs. We will reach back when we see this again.

**Comment by kggilmer** [comment] 2022-01-21 19:16
thanks for the update @mjindalmotiv8 .  I've just now tried with 7 instances and was unable to repro the bug.  If you're able to reproduce it again, providing the trace log of the response would be very helpful in root-causing the problem.  Also we may be able to get the response if you can provide the returned `requestId` assocated with a failure case.  Feel free to email me the response directly if you prefer: kggilmer at amazon.com

**Comment by aajtodd** [comment] 2022-02-24 20:00
We have had a number of issues related to the default CRT HTTP engine that have been fixed recently. One of which could explain the behavior (#528).

I'm going to go ahead and close this since you aren't seeing it anymore and may be OBE now. Please open a new issue if you encounter this again.

**Closed by aajtodd** 2022-02-24 20:00 UTC
Labels: bug
