### ISSUE TITLE
S3Exception: STREAMING-AWS4-HMAC-SHA256-PAYLOAD not implemented

### ISSUE THREAD

**Issue by ScottPierce** [awslabs/aws-sdk-kotlin#949] opened 2023-06-13 17:26 UTC
### Describe the bug

We've started getting the following error:

```
Exception in thread "main" aws.sdk.kotlin.services.s3.model.S3Exception: STREAMING-AWS4-HMAC-SHA256-PAYLOAD not implemented
	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.throwPutObjectError(PutObjectOperationDeserializer.kt:66)
	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt.access$throwPutObjectError(PutObjectOperationDeserializer.kt:1)
	at aws.sdk.kotlin.services.s3.transform.PutObjectOperationDeserializerKt$throwPutObjectError$1.invokeSuspend(PutObjectOperationDeserializer.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:7[50](https://github.com/joinadcentral/check-it-in/actions/runs/5258212481/jobs/9502125989#step:4:51))
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### Expected behavior

We don't get the error, and our files upload properly again.

### Current behavior

We get the error.

### Steps to Reproduce

Upload a file:

```
    suspend fun upload(
        key: String,
        content: File,
        contentType: String? = null,
        metadata: Map<String, String>? = null,
    ) {
        s3Client.putObject {
            this.bucket = this@AwsClient.bucket
            this.contentType = contentType
            this.metadata = metadata
            this.key = key
            body = content.asByteStream()
        }
    }

    suspend fun upload(
        key: String,
        content: String,
        contentType: String? = null,
        metadata: Map<String, String>? = null,
    ) {
        s3Client.putObject {
            this.bucket = this@AwsClient.bucket
            this.contentType = contentType
            this.metadata = metadata
            this.key = key
            body = ByteStream.fromString(content)
        }
    }
```

### Context

It's blocking our builds from uploading. This was working perfectly for months.

### AWS Kotlin SDK version used

0.27.0-beta

### Platform (JVM/JS/Native)

JDK 17

### Operating System and version

MacOS Ventura

**Comment by lauzadis** [comment] 2023-06-13 17:56
I'm not able to replicate this using **0.27.0-beta** and making a PutObject request which has the `STREAMING-AWS4-HMAC-SHA256-PAYLOAD` header, it succeeds for me.

Can you share more information about the request you're sending? If you configure your client with `logMode = LogMode.LogRequest`, the SDK will log the raw request sent to S3. Be sure to omit any sensitive information such as credentials. 

Did you recently upgrade? Does this work for you on previous versions of the SDK?

**Comment by ScottPierce** [comment] 2023-06-13 17:58
I did upgrade. Seems like going back to `0.17.5-beta` resolved this for us. Is there any way to select the method of upload so we can come back to the latest version?

**Comment by lauzadis** [comment] 2023-06-13 18:07
There's currently no way to select the method of upload. This `STREAMING-AWS4-HMAC-SHA256-PAYLOAD` is used for [aws-chunked uploads](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html), which was added to the SDK in v0.19.1-beta (specifically, in **smithy-kotlin** [0.14.1](https://github.com/awslabs/smithy-kotlin/blob/main/CHANGELOG.md#0141---12152022)). We don't expose a way to disable aws-chunked uploads right now, but will add it to our backlog.

Do you have any dependency on **aws.smithy.kotlin**? If so, it would also need to be updated.

If you can, it would be very useful to see the request sent to S3.

**Comment by ScottPierce** [comment] 2023-06-13 18:08
It seems that the C# SDK has a work around by setting `DisablePayloadSigning = true`. Is this possible in the Kotlin SDK? I have not found a way.

https://community.cloudflare.com/t/putobjectasync-not-working-for-r2-with-aws-s3-net-sdk/427335/2

**Comment by ScottPierce** [comment] 2023-06-13 22:48
@lauzadis Could this be a problem with the fact that we're using an s3 compatible API?

**Comment by lauzadis** [comment] 2023-06-14 14:19
Yes that is likely the cause here. We've seen issues with "S3-compatible" APIs which fail to support some feature such as `STREAMING-AWS4-HMAC-SHA256-PAYLOAD` here. We will add the ability to disable `aws-chunked` signing to the SDK.

**Comment by ScottPierce** [comment] 2023-06-15 02:31
We migrated to the Java SDK, and are just wrapping everything with `withContext(Dispatchers.IO) { }`. This seems to just work without any special configuration, and it's not clear why.

So we can evaluate for the future, what is the advantage to using the Kotlin SDK over the Java SDK?

**Comment by lauzadis** [comment] 2023-06-16 20:46
Interesting, Java SDK may have different criteria for when it begins using `aws-chunked` content encoding / `STREAMING-AWS4-HMAC-SHA256-PAYLOAD`. Take a look at [the Kotlin SDK homepage](https://aws.amazon.com/sdk-for-kotlin/) for more information about the key features of the Kotlin SDK and why you might consider using it over the Java SDK.

I'll close this issue and we'll continue tracking a method to disable `aws-chunked` encoding in #950. Thanks!

**Closed by lauzadis** 2023-06-16 20:46 UTC
Labels: bug
