### ISSUE TITLE
Variant selection guidance

### ISSUE THREAD

**Issue by johnlabarge** [awslabs/aws-sdk-kotlin#539] opened 2022-02-24 19:15 UTC
### Describe the issue

I'm getting a build problem having to do with variant aware building in gradle.  It's quite frustrating and I'm not sure how to fix it as the variant/attribute selection documentation for Gradle  is quite confusing and also this is transitive dependency of a pretty good distance e.g.: 

` > aws.sdk.kotlin:s3:0.13.0-beta > aws.sdk.kotlin:http-client-engine-crt:0.13.0-beta > aws.sdk.kotlin:http-client-engine-crt-jvm:0.13.0-beta > aws.sdk.kotlin:crt-util:0.13.0-beta > aws.sdk.kotlin:crt-util-jvm:0.13.0-bet`

I'm trying to add aws sdks to agradle plugin.  I get the following error message: 
```
``However we cannot choose between the following variants of aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3:
          - androidRuntimeElements-published
          - jvmRuntimeElements-published
        All of them match the consumer attributes:
          - Variant 'androidRuntimeElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a runtime of a library, packaged as a jar:
              - Unmatched attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a runtime of a library, packaged as a jar:
              - Unmatched attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'androidApiElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library, packaged as a jar:
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'commonMainMetadataElements' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'jvmApiElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library, packaged as a jar:
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'metadataApiElements' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')

```

### Steps to Reproduce

I have a gradle plugin that I'm trying to build. The gradle plugin will scaffold a Dev environment in AWS for extending the developer's environment into AWS for testing and deployments.  

Thus I have two projects one is 1) the plugin 2) the empty sub project that is meant to hold properties for the plugin tasks. 

I'm at the very beginning just trying to get my SSO auth working and I can't even build.  Thinking of bagging the gradle idea and just reverting to python, honestly. 

### Current behavior

gradle build just fails :(

### AWS Kotlin SDK version used

0.13.0-beta

### Platform (JVM/JS/Native)

JVM

### Operating System and version

Mac OS

**Comment by aajtodd** [comment] 2022-02-24 19:57
@johnlabarge 

Variant selection docs are indeed confusing.

Anyway you can share some or all of your gradle configuration?

Typically the way to handle these is we need to give gradle more information to choose the correct variant for our use. 

If you are not running in Android you probably want to set something like this:

```kotlin

configurations.all {
    attributes {
        attribute(
                TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE,
                objects.named(TargetJvmEnvironment.STANDARD_JVM)
        )
    }
}
```

**Comment by johnlabarge** [comment] 2022-02-24 20:17
@aajtodd I appreciate the quick suggestions.  I have two gradle projects 1) the plugin and 2) the shell subproject (that is part of larger) the former I just add the plugin I'm trying to use to it. 

Which project does this snippet belong in?

**Comment by aajtodd** [comment] 2022-02-24 20:19
Most likely whatever project you are trying to consume `aws.sdk.kotlin:s3:0.13.0-beta` in.

**Comment by johnlabarge** [comment] 2022-02-24 20:26
It didn't work in either :(.

**Comment by aajtodd** [comment] 2022-02-24 20:30
Did you get a different output message by chance? Are you applying the Kotlin plugin? Is this code public somewhere or can you share the gradle configuration?

**Comment by johnlabarge** [comment] 2022-02-24 22:08
So sorry it took me a little while to create this https://github.com/johnlabarge/kotlin-aws-plugin.  It has the plugin project and the empty project sanitized.  Current message is as follows: 
`A problem occurred configuring project ':app'.
> Could not resolve all files for configuration ':app:classpath'.
   > Could not resolve aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3.
     Required by:
         project :app > com.jlb.devcloud:com.jlb.devcloud.gradle.plugin:0.0.1 > com.jlb.devcloud:plugin:0.0.1 > aws.sdk.kotlin:s3:0.13.0-beta > aws.sdk.kotlin:aws-signing:0.13.0-beta > aws.sdk.kotlin:aws-signing-jvm:0.13.0-beta
         project :app > com.jlb.devcloud:com.jlb.devcloud.gradle.plugin:0.0.1 > com.jlb.devcloud:plugin:0.0.1 > aws.sdk.kotlin:s3:0.13.0-beta > aws.sdk.kotlin:http-client-engine-crt:0.13.0-beta > aws.sdk.kotlin:http-client-engine-crt-jvm:0.13.0-beta > aws.sdk.kotlin:crt-util:0.13.0-beta > aws.sdk.kotlin:crt-util-jvm:0.13.0-beta
      > The consumer was configured to find a runtime of a library compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.4'. However we cannot choose between the following variants of aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3:
          - androidRuntimeElements-published
          - jvmRuntimeElements-published
        All of them match the consumer attributes:
          - Variant 'androidRuntimeElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a runtime of a library, packaged as a jar:
              - Unmatched attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a runtime of a library, packaged as a jar:
              - Unmatched attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
        The following variants were also considered but didn't match the requested attributes:
          - Variant 'androidApiElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library, packaged as a jar:
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'commonMainMetadataElements' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'jvmApiElements-published' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library, packaged as a jar:
              - Incompatible because this component declares an API of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')
          - Variant 'metadataApiElements' capability aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3 declares a library:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component and the consumer needed a runtime of a component
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.4')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
`

**Comment by aajtodd** [comment] 2022-02-25 22:05
@johnlabarge 

Quick update. I was able to recreate with the project you provided. Unfortunately I have no quick answers. 

It would seem that the issue is related to Gradle and how it propagates dependencies. I can see that the plugin build compiles fine and resolves the desired dependency variant with the configuration set:

```kotlin
configurations.all {
    attributes {
        attribute(
            TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE,
            objects.named(TargetJvmEnvironment.STANDARD_JVM)
        )
    }
}
```

It would seem though that applying the plugin downstream in `app`:

```kotlin
plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id 'application'
    id 'com.jlb.devcloud' version '0.0.1'
}
```

Results in the failure you are seeing. It is basically saying it can't resolve the classpath for the buildscript itself due to the plugin dependency on `s3` (which has a transitive dependency on `aws-crt-kotlin` which has a JVM and Android variant).

I would have thought that adding the following to `app/build.gradle` would solve it but apparently not.

```kotlin
buildscript {
     configurations.all {
         attributes {
             attribute(TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE, objects.named(TargetJvmEnvironment, TargetJvmEnvironment.STANDARD_JVM))
         }
     }
}
```

This would only be a temporary workaround anyway because as a plugin developer you obviously don't want to force every consumer of your plugin to have to do this.

------

This issue will go away down the road a bit but that doesn't help you immediately. 

I am getting to the end of my gradle knowledge here it would seem though. I'm not sure how to enforce a particular transitive dependency to use a specific variant for downstream consumers. I'll do some more poking but I can't promise a solution to this in the near term.

**Comment by Vampire** [comment] 2022-02-26 03:13
If you configure attributes on configurations, then this is just a local thing.
If you want it published and used by downstream projects, define the attributes on the dependency.
In your case I'd say the proper solution is to define a constraint for that transitive dependency that defines the attribute.
This diff will make the `empty-project` work properly out of the box:
```diff
diff --git a/devcloud/plugin/build.gradle.kts b/devcloud/plugin/build.gradle.kts
index 75c6b49..adae961 100644
--- a/devcloud/plugin/build.gradle.kts
+++ b/devcloud/plugin/build.gradle.kts
@@ -6,7 +6,9 @@
  * User Manual available at https://docs.gradle.org/7.4/userguide/custom_plugins.html
  * This project uses @Incubating APIs which are subject to change.
  */
+import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
 import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
+import org.jetbrains.kotlin.project.model.KotlinPlatformTypeAttribute

 plugins {
     // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
@@ -31,6 +33,16 @@ dependencies {
     // Use the Kotlin JDK 8 standard library.
     implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
     implementation("aws.sdk.kotlin:s3:0.13.0-beta")
+    constraints {
+        implementation("aws.sdk.kotlin.crt:aws-crt-kotlin:0.5.3") {
+            attributes {
+                attribute(
+                    KotlinPlatformType.attribute,
+                    KotlinPlatformType.jvm
+                )
+            }
+        }
+    }
 }

 testing {
@@ -85,14 +97,5 @@ tasks.withType<KotlinCompile>() {
     }
 }

-configurations.all {
-    attributes {
-        attribute(
-            TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE,
-            objects.named(TargetJvmEnvironment.STANDARD_JVM)
-        )
-    }
-}
-
 group = "com.jlb.devcloud"
 version = "0.0.1"
```

**Comment by aajtodd** [comment] 2022-03-01 14:19
Closing this then as we have a possible solution should you come back to it.

**Closed by aajtodd** 2022-03-01 14:19 UTC
Labels: guidance
